name: C/C++ CI

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  merge_group:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    name: Integration CI LLVM ${{ matrix.llvm }} ${{ matrix.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        llvm: ["15", "16", "17", "18", "19", "20", "21"]
        build: ["Release"] # "RelWithDebInfo"
        os: [ubuntu-22.04]
    
    timeout-minutes: 45
    
    steps:
    - name: add llvm 
      run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-get install -y libmpfr-dev
          sudo apt-add-repository "deb http://apt.llvm.org/`lsb_release -c | cut -f2`/ llvm-toolchain-`lsb_release -c | cut -f2`-${{ matrix.llvm }} main" || true
          sudo apt-get install -y cmake gcc g++ llvm-${{ matrix.llvm }}-dev libomp-${{ matrix.llvm }}-dev lld-${{ matrix.llvm }} clang-${{ matrix.llvm }} libclang-${{ matrix.llvm }}-dev libeigen3-dev libboost-dev libzstd-dev
          sudo python3 -m pip install --upgrade pip lit
    - uses: actions/checkout@v4
    - name: mkdir
      run: rm -rf build && mkdir build
    - name: cmake
      working-directory: build
      run: cmake ../enzyme -DLLVM_EXTERNAL_LIT=`which lit` -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm }}/lib/cmake/llvm
    - name: make
      run: cd build && make -j `nproc` LLVMEnzyme-${{ matrix.llvm }} ClangEnzyme-${{ matrix.llvm }} LLDEnzyme-${{ matrix.llvm }}  
    - name: make test-cmake
      working-directory: build
      run: make -j `nproc` test-cmake
    - name: make check-enzyme-integration
      working-directory: build
      run: make -j `nproc` check-enzyme-integration
      
    - name: Update Nightly Release
      uses: ncipollo/release-action@v1
      if: ${{ !cancelled() && github.ref == 'refs/heads/main' }} 
      with:
        tag: nightly
        name: Nightly Release
        body: "Latest nightly build of Enzyme."
        artifacts: "build/Enzyme/LLVMEnzyme-${{ matrix.llvm }}*,build/Enzyme/ClangEnzyme-${{ matrix.llvm }},build/Enzyme/LLDEnzyme-${{ matrix.llvm }}"
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
